Repository cunla/fakeredis-py, pull requests merged in 2023-05, with the labels that each got.

#147 Implement XREAD
  .github/workflows/publish.yml
  .github/workflows/test.yml
  docs/about/changelog.md
  docs/redis-commands/Redis.md
  docs/requirements.txt
  fakeredis/_command_args_parsing.py
  fakeredis/_stream.py
  fakeredis/commands_mixins/bitmap_mixin.py
  fakeredis/commands_mixins/connection_mixin.py
  fakeredis/commands_mixins/generic_mixin.py
  fakeredis/commands_mixins/hash_mixin.py
  fakeredis/commands_mixins/list_mixin.py
  fakeredis/commands_mixins/pubsub_mixin.py
  fakeredis/commands_mixins/scripting_mixin.py
  fakeredis/commands_mixins/server_mixin.py
  fakeredis/commands_mixins/streams_mixin.py
  fakeredis/commands_mixins/string_mixin.py
  poetry.lock
  pyproject.toml
  test/test_mixins/test_streams_commands.py
  test/test_redis_asyncio.py
Labels: enhancement

#152 Fixed xadd timestamp (fixes #151)
  fakeredis/_stream.py
  test/test_mixins/test_streams_commands.py
Labels: bug

#153 Implement XDEL #150
  docs/about/changelog.md
  fakeredis/_stream.py
  fakeredis/commands_mixins/streams_mixin.py
  pyproject.toml
  test/conftest.py
  test/test_mixins/test_streams_commands.py
  test/test_redis_asyncio.py
Labels: enhancement, chore
